<?php

namespace AppBundle\Repository;

/**
 * ConflitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConflitRepository extends \Doctrine\ORM\EntityRepository
{
}
