<?php

namespace AppBundle\Repository;

/**
 * SoldatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoldatRepository extends \Doctrine\ORM\EntityRepository
{
}
